stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: "/certs"

publish:
  image: docker:18.09
  stage: publish
  services:
    - docker:18.09-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - cd streamlit_app
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  environment:
    name: production
    url: http://80.93.46.242

deploy:
  image: docker:18.09
  stage: deploy
  tags:
    - deployment
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TAG_COMMIT
    - docker tag $TAG_COMMIT $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:production
    - docker container rm -f logapp || true
    - docker images
    - docker run -d -p 80:8501 --name dronelab-logging-app_logapp $TAG_COMMIT"
  environment:
    name: production
    url: http://80.93.46.242
  only:
    - master
    - main

