version: '3.1'

services:
  db:
    image: mysql/mysql-server:8.0.28
    restart: unless-stopped
    container_name: mysql
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs_db
      MYSQL_USER: cs
      MYSQL_PASSWORD: cs123
      MYSQL_ROOT_HOST: '%' # wildcard to allow anyone IP to connect as root
    ports:
      - "3307:3306"
    volumes:
      - /opt/containers/mysql/conf.d:/etc/mysql/conf.d
      - /opt/containers/mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: unless-stopped
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    expose:
      - "80"
    ports:
      - "8081:80"
  logapp:
    image: gcr.web.fh-kufstein.ac.at/golecpatrik/dronelab-logging-app:latest
    restart: unless-stopped
    container_name: logapp
    links:
      - db
    expose:
      - "8501"
    ports:
      - "80:8501"

